[tool.briefcase]
project_name = "passwordhider"
bundle = "io.github.tusharhero"
version = "0.0.1"
url = "https://tusharhero.github.io/txtt-hider-w-passwd"
license = "MIT license"
author = 'Tushar Maharana'
author_email = "tusharmaharana44676@gmail.com"

[tool.briefcase.app.passwordhider]
formal_name = "passwordhider"
description = "Hide text using password, and also unhides ."
icon = "src/passwordhider/resources/passwordhider"
sources = ['src/passwordhider']
requires = [
]


[tool.briefcase.app.passwordhider.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.passwordhider.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.passwordhider.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.passwordhider.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.passwordhider.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
